export enum FunctionEnum {
  PRAESES,
  VICE_PRAESES,
  QUAESTOR,
  CANTOR,
  AB_ACTIS,
  SCHACTENMEESTER,
  SCHACHTENTEMMER,
  ZEDENMEESTER,
  FEEST,
  S_O_C,
  P_R,
  REDACTOR,
  MEDIA,
  WEBMASTER,
  RESIDENT_DJ,
  METER,
  PETER,
  ERE_LID,
  ERE_PRAESES,
  OUWE_ZAK
}

export const Function2LabelMapping: Record<FunctionEnum, string> = {
  [FunctionEnum.PRAESES]: "Praeses",
  [FunctionEnum.VICE_PRAESES]: "Vice-Praeses",
  [FunctionEnum.QUAESTOR]: "Quaestor",
  [FunctionEnum.CANTOR]: "Cantor",
  [FunctionEnum.AB_ACTIS]: "Ab-Actis",
  [FunctionEnum.SCHACTENMEESTER]: "Schachtenmeester",
  [FunctionEnum.SCHACHTENTEMMER]: "Schachtentemmer",
  [FunctionEnum.ZEDENMEESTER]: "Zedenmeester",
  [FunctionEnum.FEEST]: "Feest",
  [FunctionEnum.S_O_C]: "S.O.C.",
  [FunctionEnum.P_R]: "P.R.",
  [FunctionEnum.REDACTOR]: "Redactor",
  [FunctionEnum.MEDIA]: "Media",
  [FunctionEnum.WEBMASTER]: "Webmaster",
  [FunctionEnum.RESIDENT_DJ]: "Resident DJ",
  [FunctionEnum.METER]: "Meter",
  [FunctionEnum.PETER]: "Peter",
  [FunctionEnum.ERE_LID]: "Ere-Lid",
  [FunctionEnum.ERE_PRAESES]: "Ere-Praeses",
  [FunctionEnum.OUWE_ZAK]: "Ouwe-Zak",
};